apiRules:
- include:
    uidRegex: ^DrivingErrors
    type: Namespace
- include:
    uidRegex: ^DrivingErrors\.UI
    type: Namespace
- include:
    uidRegex: ^DrivingErrors\.UI\.Buttons
    type: Namespace
- include:
    uidRegex: ^DrivingErrors\.ErrorDetection
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace